// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp9cRr1eBBaWVd8A9caFWZcbQDjGDZOW4',
    appId: '1:948424387443:web:b33eda5a27d68150467306',
    messagingSenderId: '948424387443',
    projectId: 'twitterclone-3fc55',
    authDomain: 'twitterclone-3fc55.firebaseapp.com',
    storageBucket: 'twitterclone-3fc55.appspot.com',
    measurementId: 'G-C0TNT5VM40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1WfAwwWSCw25cx6U34cuOTYT8_6UlI3E',
    appId: '1:948424387443:android:2dffe0199c8dde56467306',
    messagingSenderId: '948424387443',
    projectId: 'twitterclone-3fc55',
    storageBucket: 'twitterclone-3fc55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWY9CuZiVfMDFZMaIcoOiy7GG3rSnXp1Y',
    appId: '1:948424387443:ios:393117f026054fa9467306',
    messagingSenderId: '948424387443',
    projectId: 'twitterclone-3fc55',
    storageBucket: 'twitterclone-3fc55.appspot.com',
    iosClientId: '948424387443-fnk10a4t9j5kbpia5oj1d7hdo6bokd1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWY9CuZiVfMDFZMaIcoOiy7GG3rSnXp1Y',
    appId: '1:948424387443:ios:393117f026054fa9467306',
    messagingSenderId: '948424387443',
    projectId: 'twitterclone-3fc55',
    storageBucket: 'twitterclone-3fc55.appspot.com',
    iosClientId: '948424387443-fnk10a4t9j5kbpia5oj1d7hdo6bokd1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );
}
